#!/usr/bin/env bash
# Self-contained test harness for the DATA CENTER triage skill scripts.
#
# Same approach as the Cloud agent's tests (no framework: a fake `curl` on PATH
# replays a fixture for GETs and records the request URL/headers/body for
# writes), but the assertions pin the DC-specific wire shapes:
#   - REST API base is /rest/api/2 (not v3)
#   - Authorization: Bearer (not Basic)
#   - comment body is a plain string (not ADF {type:doc,...})
#   - assignee is {"name": ...} (not {"accountId": ...})
# plus the shared security behaviors (allowed-set guard, fail-closed, convergent
# no-op, trigger-label-only remove, gitlab structured output, loopMarker contract).
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$HERE/.." && pwd)"
SCRIPTS="$SKILL_DIR/scripts"
FIX="$HERE/fixtures"

PASS=0; FAIL=0
ok()   { PASS=$((PASS+1)); echo "ok   - $1"; }
nope() { FAIL=$((FAIL+1)); echo "FAIL - $1"; [ -n "${2:-}" ] && echo "       $2"; }

# --- fake curl ----------------------------------------------------------------
# Record URL, every -H header, and the --data body; reply with the fixture file.
STUB_DIR="$(mktemp -d)"
trap 'rm -rf "$STUB_DIR"' EXIT
cat > "$STUB_DIR/curl" <<'STUB'
#!/usr/bin/env bash
cap="${CURL_CAPTURE:-/dev/null}"
body=""; url=""; prev=""
for a in "$@"; do
  case "$prev" in
    --data) body="$a" ;;
    -H)     echo "HDR=$a" >> "$cap" ;;
  esac
  case "$a" in
    http*|https*) url="$a" ;;
  esac
  prev="$a"
done
{ echo "URL=$url"; echo "BODY=$body"; } >> "$cap"
[ -n "${CURL_FIXTURE:-}" ] && cat "$CURL_FIXTURE"
exit 0
STUB
chmod +x "$STUB_DIR/curl"
export PATH="$STUB_DIR:$PATH"

# --- common env (DC: Bearer PAT, no email) ------------------------------------
export JIRA_BASE_URL="https://jira.example.internal"
export JIRA_API_TOKEN="dc-personal-access-token"
export TRIAGE_CONFIG="$HERE/config.test.json"
unset JIRA_EMAIL JIRA_AUTH_SCHEME 2>/dev/null || true

run_jira()  { CURL_CAPTURE="$1" CURL_FIXTURE="$2"; export CURL_CAPTURE CURL_FIXTURE; shift 2; bash "$SCRIPTS/jira.sh" "$@"; }

# --- D1: REST base is /rest/api/2, auth is Bearer -----------------------------
cap="$(mktemp)"
run_jira "$cap" "$FIX/issue-OPS-5.json" get OPS-5 >/dev/null 2>&1
if grep -q "URL=.*/rest/api/2/issue/OPS-5" "$cap"; then ok "D1a uses REST API v2"; else nope "D1a uses REST API v2" "$(cat "$cap")"; fi
if grep -q "HDR=Authorization: Bearer dc-personal-access-token" "$cap"; then ok "D1b Bearer PAT auth header"; else nope "D1b Bearer PAT auth header" "$(cat "$cap")"; fi
if grep -qi "HDR=Authorization: Basic" "$cap"; then nope "D1c no Basic header on DC" "$(cat "$cap")"; else ok "D1c no Basic header on DC"; fi

# --- D2: comment body is a PLAIN string, not ADF ------------------------------
cap="$(mktemp)"
run_jira "$cap" "$FIX/issue-OPS-5.json" comment OPS-5 "category=bug, severity=medium" >/dev/null 2>&1
flat="$(tr -d '\n' < "$cap")"
if echo "$flat" | grep -q 'This was generated by AI during triage'; then ok "D2a disclaimer in comment body"; else nope "D2a disclaimer in comment body" "$(cat "$cap")"; fi
if echo "$flat" | grep -q '"type":"doc"'; then nope "D2b comment is plain (no ADF)" "ADF doc node found: $(cat "$cap")"; else ok "D2b comment is plain (no ADF)"; fi

# --- D3: assignee uses {"name": ...} (username), not accountId ----------------
cap="$(mktemp)"
run_jira "$cap" "$FIX/issue-OPS-5.json" assign OPS-5 jdoe >/dev/null 2>&1
flat="$(tr -d '\n ' < "$cap")"
if echo "$flat" | grep -q '"name":"jdoe"'; then ok "D3a assignee by username {name}"; else nope "D3a assignee by username {name}" "$(cat "$cap")"; fi
if echo "$flat" | grep -q 'accountId'; then nope "D3b no accountId in assignee" "$(cat "$cap")"; else ok "D3b no accountId in assignee"; fi

# --- D4: assignee outside the allowed pool rejected ---------------------------
cap="$(mktemp)"
if out="$(run_jira "$cap" "$FIX/issue-OPS-5.json" assign OPS-5 evil-user 2>&1)"; then
  nope "D4 assignee pool enforced" "expected rejection, got: $out"
else
  echo "$out" | grep -q "not in allowed pool" && ok "D4 assignee pool enforced" || nope "D4 assignee pool enforced" "$out"
fi

# --- D5: out-of-set label rejected --------------------------------------------
cap="$(mktemp)"
if out="$(run_jira "$cap" "$FIX/issue-OPS-5.json" set-fields OPS-5 label=not-a-real-label 2>&1)"; then
  nope "D5 out-of-set label rejected" "expected non-zero exit, got success: $out"
else
  echo "$out" | grep -q "not in allowed set" && ok "D5 out-of-set label rejected" || nope "D5 out-of-set label rejected" "$out"
fi

# --- D6: fail closed when config missing --------------------------------------
cap="$(mktemp)"
if out="$(TRIAGE_CONFIG=/nonexistent/config.json run_jira "$cap" "$FIX/issue-OPS-5.json" set-fields OPS-5 priority=Low 2>&1)"; then
  nope "D6 fail-closed on missing config" "expected failure, got: $out"
else
  echo "$out" | grep -q "failing closed" && ok "D6 fail-closed on missing config" || nope "D6 fail-closed on missing config" "$out"
fi

# --- D7: convergent no-op (priority already at target) ------------------------
cap="$(mktemp)"
out="$(run_jira "$cap" "$FIX/issue-OPS-5.json" set-fields OPS-5 priority=Medium 2>&1)"
if echo "$out" | grep -q '"status":"noop"'; then
  if grep -q "URL=.*/issue/OPS-5$" "$cap"; then
    nope "D7 convergent no-op" "a PUT was issued despite no change: $(cat "$cap")"
  else
    ok "D7 convergent no-op"
  fi
else
  nope "D7 convergent no-op" "$out"
fi

# --- D8: in-set priority change issues a PUT with the right field -------------
cap="$(mktemp)"
run_jira "$cap" "$FIX/issue-OPS-5.json" set-fields OPS-5 priority=Low >/dev/null 2>&1
flat="$(tr -d '\n ' < "$cap")"
if echo "$flat" | grep -q '"priority":{"name":"Low"}'; then ok "D8 in-set priority PUT body"; else nope "D8 in-set priority PUT body" "$(cat "$cap")"; fi

# --- D9: in-set issue-type change emits the issuetype field -------------------
cap="$(mktemp)"
run_jira "$cap" "$FIX/issue-OPS-5.json" set-fields OPS-5 issuetype=Story >/dev/null 2>&1
flat="$(tr -d '\n ' < "$cap")"
if echo "$flat" | grep -q '"issuetype":{"name":"Story"}'; then ok "D9 in-set issue-type PUT body"; else nope "D9 in-set issue-type PUT body" "$(cat "$cap")"; fi

# --- D10: Basic auth opt-in (JIRA_AUTH_SCHEME=basic) --------------------------
cap="$(mktemp)"
CURL_CAPTURE="$cap" CURL_FIXTURE="$FIX/issue-OPS-5.json" \
  JIRA_AUTH_SCHEME=basic JIRA_EMAIL=botuser bash "$SCRIPTS/jira.sh" get OPS-5 >/dev/null 2>&1
if grep -qi "HDR=Authorization: Basic " "$cap"; then ok "D10 Basic auth opt-in works"; else nope "D10 Basic auth opt-in works" "$(cat "$cap")"; fi

# --- D11: transition outside the allowed set is rejected ----------------------
cat > "$STUB_DIR/curl" <<'STUB'
#!/usr/bin/env bash
cap="${CURL_CAPTURE:-/dev/null}"; echo "called" >> "$cap"; exit 0
STUB
chmod +x "$STUB_DIR/curl"
cap="$(mktemp)"
if out="$(CURL_CAPTURE="$cap" bash "$SCRIPTS/jira.sh" transition OPS-5 999 2>&1)"; then
  nope "D11 transition allowed-set enforced" "expected rejection, got: $out"
else
  echo "$out" | grep -q "not in allowed set" && ok "D11 transition allowed-set enforced" || nope "D11 transition allowed-set enforced" "$out"
fi

# --- D12: in-set transition is permitted (reaches the API) --------------------
cap="$(mktemp)"
CURL_CAPTURE="$cap" bash "$SCRIPTS/jira.sh" transition OPS-5 31 >/dev/null 2>&1
grep -q "called" "$cap" && ok "D12 in-set transition permitted" || nope "D12 in-set transition permitted" "no API call made"

# --- D13: remove-label only permits the trigger label ------------------------
cap="$(mktemp)"
if out="$(CURL_CAPTURE="$cap" bash "$SCRIPTS/jira.sh" remove-label OPS-5 ready-for-agent 2>&1)"; then
  nope "D13 remove-label restricted to trigger" "expected rejection, got: $out"
else
  echo "$out" | grep -q "only permitted for the trigger label" && ok "D13 remove-label restricted to trigger" || nope "D13 remove-label restricted to trigger" "$out"
fi

# --- D14: remove-label permits the triage trigger label ----------------------
cap="$(mktemp)"
CURL_CAPTURE="$cap" bash "$SCRIPTS/jira.sh" remove-label OPS-5 triage >/dev/null 2>&1
grep -q "called" "$cap" && ok "D14 remove-label clears triage flag" || nope "D14 remove-label clears triage flag" "no API call made"

# --- D14b: a newly-allowed label ("docs") is accepted and written -------------
# Demonstrates the rubric+config pattern from the configure guide: once "docs" is
# in config.test.json `labels`, set-fields writes it (fixture has no "docs" label,
# so it's a real add → a PUT carrying update.labels[{add:"docs"}]).
cat > "$STUB_DIR/curl" <<'STUB'
#!/usr/bin/env bash
cap="${CURL_CAPTURE:-/dev/null}"
body=""; url=""; prev=""
for a in "$@"; do
  case "$prev" in --data) body="$a" ;; esac
  case "$a" in http*|https*) url="$a" ;; esac
  prev="$a"
done
{ echo "URL=$url"; echo "BODY=$body"; } >> "$cap"
[ -n "${CURL_FIXTURE:-}" ] && cat "$CURL_FIXTURE"
exit 0
STUB
chmod +x "$STUB_DIR/curl"
cap="$(mktemp)"
run_jira "$cap" "$FIX/issue-OPS-5.json" set-fields OPS-5 label=docs >/dev/null 2>&1
flat="$(tr -d '\n ' < "$cap")"
if echo "$flat" | grep -q '"labels":\[{"add":"docs"}\]'; then ok "D14b newly-allowed 'docs' label is written"; else nope "D14b newly-allowed 'docs' label is written" "$(cat "$cap")"; fi

# --- D15: gitlab.sh emits ONLY {component, owner} (shared, flavor-agnostic) ---
cat > "$STUB_DIR/curl" <<'STUB'
#!/usr/bin/env bash
cat <<'JSON'
{"name":"payments","namespace":{"full_path":"team/backend"},"description":"SECRET internal notes","readme":"do not leak me"}
JSON
STUB
chmod +x "$STUB_DIR/curl"
export GITLAB_BASE_URL="https://gitlab.example.internal"
export GITLAB_READ_TOKEN="ro-token"
out="$(bash "$SCRIPTS/gitlab.sh" route team/payments 2>&1)"
keys="$(echo "$out" | jq -r 'keys | join(",")' 2>/dev/null)"
if [ "$keys" = "component,owner" ] && ! echo "$out" | grep -qi "secret\|leak\|readme\|description"; then
  ok "D15 gitlab structured output only"
else
  nope "D15 gitlab structured output only" "got: $out"
fi

# --- D16: agent loopMarker is a substring of jira.sh disclaimer ---------------
SKILL_MARKER="$(grep -oE '^loopMarker: .+$' "$SKILL_DIR/SKILL.md" 2>/dev/null | sed 's/^loopMarker: //')"
SKILL_DISCLAIMER="$(grep -oE 'This was generated by AI during triage\.' "$SCRIPTS/jira.sh" | head -1)"
if [ -n "$SKILL_MARKER" ] && printf '%s' "$SKILL_DISCLAIMER" | grep -qF "$SKILL_MARKER"; then
  ok "D16 agent loopMarker is a substring of jira.sh disclaimer"
else
  nope "D16 agent loopMarker is a substring of jira.sh disclaimer" "marker='$SKILL_MARKER' skill='$SKILL_DISCLAIMER'"
fi

echo "-----"
echo "PASS=$PASS FAIL=$FAIL"
[ "$FAIL" -eq 0 ]
