'use strict';

const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');

const {
  loadAgentDef,
  renderPrompt,
  splitFrontmatter,
  parseFrontmatter,
  _resetCache,
} = require('../lib/agent-def');

function withSkill(contents, fn) {
  _resetCache();
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'agentdef-'));
  fs.writeFileSync(path.join(dir, 'SKILL.md'), contents);
  try {
    return fn(dir);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
    _resetCache();
  }
}

// --- frontmatter splitting ---------------------------------------------------
test('splitFrontmatter separates YAML header from body', () => {
  const { yaml, body } = splitFrontmatter('---\nname: x\n---\n# Title\nprose');
  assert.match(yaml, /name: x/);
  assert.match(body, /# Title/);
});

test('splitFrontmatter passes through a body with no frontmatter', () => {
  const { yaml, body } = splitFrontmatter('# No frontmatter here');
  assert.strictEqual(yaml, null);
  assert.match(body, /No frontmatter/);
});

// --- minimal YAML parser -----------------------------------------------------
test('parseFrontmatter handles scalars, block scalars, and lists', () => {
  const fm = parseFrontmatter(
    ['name: jira-triage', 'prompt: |', '  Line one {{key}}', '  Line two', 'actors: [A, B]', 'list:', '  - x', '  - y'].join(
      '\n'
    )
  );
  assert.strictEqual(fm.name, 'jira-triage');
  assert.strictEqual(fm.prompt, 'Line one {{key}}\nLine two');
  assert.deepStrictEqual(fm.actors, ['A', 'B']);
  assert.deepStrictEqual(fm.list, ['x', 'y']);
});

// --- loadAgentDef ------------------------------------------------------------
test('loadAgentDef reads prompt, loopMarker, authorizedActors, trustTools, model', () => {
  const md = [
    '---',
    'name: my-agent',
    'prompt: |',
    '  Do the thing for {{key}}, then stop.',
    'loopMarker: GENERATED BY AI',
    'authorizedActors: [actor-1, actor-2]',
    'trustTools: read,execute_bash',
    'model: anthropic/claude-sonnet-4-6',
    '---',
    '# Rubric',
    'body prose',
  ].join('\n');
  withSkill(md, (dir) => {
    const def = loadAgentDef(dir);
    assert.strictEqual(def.name, 'my-agent');
    assert.match(def.prompt, /Do the thing for \{\{key\}\}/);
    assert.strictEqual(def.loopMarker, 'GENERATED BY AI');
    assert.ok(def.authorizedActors.has('actor-1') && def.authorizedActors.has('actor-2'));
    assert.strictEqual(def.trustTools, 'read,execute_bash');
    assert.strictEqual(def.model, 'anthropic/claude-sonnet-4-6');
    assert.match(def.body, /# Rubric/);
  });
});

test('loadAgentDef throws when the skill declares no prompt', () => {
  withSkill('---\nname: no-prompt\n---\nbody', (dir) => {
    assert.throws(() => loadAgentDef(dir), /no `prompt`/);
  });
});

// --- renderPrompt ------------------------------------------------------------
test('renderPrompt substitutes known vars and leaves unknown placeholders intact', () => {
  assert.strictEqual(renderPrompt('Triage {{key}} now', { key: 'KAN-9' }), 'Triage KAN-9 now');
  // unknown placeholder is left visible (not silently blanked)
  assert.strictEqual(renderPrompt('Hi {{missing}}', { key: 'x' }), 'Hi {{missing}}');
});
