'use strict';

const { test } = require('node:test');
const assert = require('node:assert');
const crypto = require('crypto');
const {
  verifySignature,
  verifySharedSecret,
  triageLabelAdded,
  decide,
  AUTOMATION_LABEL_EVENT,
} = require('../listener/gate');
const { DedupeCache, SpawnLimiter } = require('../listener/limits');

const SECRET = 'a'.repeat(64);
function sign(body, secret = SECRET) {
  return 'sha256=' + crypto.createHmac('sha256', secret).update(body).digest('hex');
}

// --- HMAC (R10/R10a) ---------------------------------------------------------
test('valid signature over the exact raw body is accepted', () => {
  const body = Buffer.from(JSON.stringify({ webhookEvent: 'jira:issue_created' }));
  assert.strictEqual(verifySignature(body, sign(body), SECRET), true);
});

test('tampered body is rejected', () => {
  const body = Buffer.from('{"a":1}');
  const sig = sign(body);
  const tampered = Buffer.from('{"a":2}');
  assert.strictEqual(verifySignature(tampered, sig, SECRET), false);
});

test('missing signature header is rejected', () => {
  const body = Buffer.from('{}');
  assert.strictEqual(verifySignature(body, undefined, SECRET), false);
});

test('wrong algorithm prefix is rejected', () => {
  const body = Buffer.from('{}');
  const sig = sign(body).replace('sha256=', 'md5=');
  assert.strictEqual(verifySignature(body, sig, SECRET), false);
});

test('length-mismatched signature is rejected without throwing', () => {
  const body = Buffer.from('{}');
  assert.strictEqual(verifySignature(body, 'sha256=abcd', SECRET), false);
});

// --- shared-secret auth (R10a-bis, Automation path) --------------------------
test('correct shared secret is accepted', () => {
  assert.strictEqual(verifySharedSecret('s3cret-token', 's3cret-token'), true);
});

test('wrong shared secret is rejected', () => {
  assert.strictEqual(verifySharedSecret('nope', 's3cret-token'), false);
});

test('missing shared secret header or unset secret is rejected', () => {
  assert.strictEqual(verifySharedSecret(undefined, 's3cret-token'), false);
  assert.strictEqual(verifySharedSecret('s3cret-token', ''), false);
});

test('length-mismatched shared secret is rejected without throwing (constant-time guard)', () => {
  assert.strictEqual(verifySharedSecret('short', 'a-much-longer-secret'), false);
});

// --- loop guard (R7) ---------------------------------------------------------
const baseState = () => ({
  botAccountId: 'BOT-1',
  authorizedActors: new Set(['ALLOWED-1']),
  triageMarker: 'This was generated by AI during triage.',
});

test('webhook from the bot account is dropped (loop guard)', () => {
  const payload = {
    webhookEvent: 'jira:issue_updated',
    user: { accountId: 'BOT-1' },
    issue: { key: 'KAN-5' },
    changelog: { items: [{ field: 'labels', fromString: '', toString: 'triage' }] },
  };
  assert.deepStrictEqual(decide(payload, baseState()).action, 'drop');
});

test('self-write recognized statelessly via marker even with no botAccountId yet', () => {
  const state = { ...baseState(), botAccountId: null };
  const payload = {
    webhookEvent: 'jira:issue_updated',
    user: { accountId: 'SOMEONE' },
    issue: { key: 'KAN-5' },
    comment: { body: '> *This was generated by AI during triage.* ...' },
    changelog: { items: [{ field: 'labels', fromString: '', toString: 'triage' }] },
  };
  const v = decide(payload, state);
  assert.strictEqual(v.action, 'drop');
  assert.match(v.reason, /marker/);
});

// --- eligibility (R6) --------------------------------------------------------
test('issue_created spawns', () => {
  const payload = { webhookEvent: 'jira:issue_created', user: { accountId: 'X' }, issue: { key: 'KAN-9' } };
  assert.deepStrictEqual(decide(payload, baseState()), { action: 'spawn', key: 'KAN-9' });
});

test('issue_updated WITHOUT triage label is dropped as ineligible', () => {
  const payload = {
    webhookEvent: 'jira:issue_updated',
    user: { accountId: 'ALLOWED-1' },
    issue: { key: 'KAN-5' },
    changelog: { items: [{ field: 'summary', fromString: 'a', toString: 'b' }] },
  };
  assert.strictEqual(decide(payload, baseState()).action, 'drop');
});

test('triageLabelAdded detects add vs pre-existing', () => {
  assert.strictEqual(triageLabelAdded({ changelog: { items: [{ field: 'labels', fromString: 'x', toString: 'x triage' }] } }), true);
  assert.strictEqual(triageLabelAdded({ changelog: { items: [{ field: 'labels', fromString: 'triage', toString: 'triage done' }] } }), false);
});

// --- authorization (R6b) -----------------------------------------------------
test('triage label added by UNAUTHORIZED actor is dropped', () => {
  const payload = {
    webhookEvent: 'jira:issue_updated',
    user: { accountId: 'OUTSIDER' },
    issue: { key: 'KAN-5' },
    changelog: { items: [{ field: 'labels', fromString: '', toString: 'triage' }] },
  };
  const v = decide(payload, baseState());
  assert.strictEqual(v.action, 'drop');
  assert.match(v.reason, /unauthorized/);
});

test('triage label added by ALLOWED actor spawns', () => {
  const payload = {
    webhookEvent: 'jira:issue_updated',
    user: { accountId: 'ALLOWED-1' },
    issue: { key: 'KAN-5' },
    changelog: { items: [{ field: 'labels', fromString: '', toString: 'triage' }] },
  };
  assert.deepStrictEqual(decide(payload, baseState()), { action: 'spawn', key: 'KAN-5' });
});

// --- Automation rule event (R10a-bis) ----------------------------------------
test('automation label-added event from ALLOWED actor spawns (no changelog needed)', () => {
  const payload = {
    webhookEvent: AUTOMATION_LABEL_EVENT,
    user: { accountId: 'ALLOWED-1' },
    issue: { key: 'KAN-7' },
  };
  assert.deepStrictEqual(decide(payload, baseState()), { action: 'spawn', key: 'KAN-7' });
});

test('automation label-added event from UNAUTHORIZED actor is dropped (R6b still applies)', () => {
  const payload = {
    webhookEvent: AUTOMATION_LABEL_EVENT,
    user: { accountId: 'OUTSIDER' },
    issue: { key: 'KAN-7' },
  };
  const v = decide(payload, baseState());
  assert.strictEqual(v.action, 'drop');
  assert.match(v.reason, /unauthorized/);
});

test('automation label-added event still honors the loop guard (bot self-write)', () => {
  const payload = {
    webhookEvent: AUTOMATION_LABEL_EVENT,
    user: { accountId: 'BOT-1' },
    issue: { key: 'KAN-7' },
  };
  assert.strictEqual(decide(payload, baseState()).action, 'drop');
});

// --- dedupe (R8) -------------------------------------------------------------
test('duplicate webhook identifier is detected; TTL floor is >=24h', () => {
  let now = 1_000_000;
  const c = new DedupeCache(60_000, () => now); // ask for 60s, floor forces 24h
  assert.strictEqual(c.seenBefore('id-1'), false);
  assert.strictEqual(c.seenBefore('id-1'), true);
  now += 23 * 60 * 60 * 1000; // 23h later — still within the 24h floor
  assert.strictEqual(c.seenBefore('id-1'), true);
  now += 2 * 60 * 60 * 1000; // now 25h — expired
  assert.strictEqual(c.seenBefore('id-1'), false);
});

test('absent identifier is not deduped (let through)', () => {
  const c = new DedupeCache();
  assert.strictEqual(c.seenBefore(undefined), false);
  assert.strictEqual(c.seenBefore(''), false);
});

// --- limiter (R10c) ----------------------------------------------------------
test('semaphore blocks beyond max concurrency', () => {
  const l = new SpawnLimiter({ maxConcurrent: 2, ceiling: 100 });
  assert.strictEqual(l.tryAcquire().ok, true);
  assert.strictEqual(l.tryAcquire().ok, true);
  const third = l.tryAcquire();
  assert.strictEqual(third.ok, false);
  assert.strictEqual(third.reason, 'concurrency');
  l.release();
  assert.strictEqual(l.tryAcquire().ok, true);
});

test('global rate ceiling blocks a storm regardless of concurrency', () => {
  let now = 0;
  const l = new SpawnLimiter({ maxConcurrent: 100, ceiling: 3, windowMs: 1000, dailyBudget: 1000, now: () => now });
  assert.strictEqual(l.tryAcquire().ok, true);
  l.release();
  assert.strictEqual(l.tryAcquire().ok, true);
  l.release();
  assert.strictEqual(l.tryAcquire().ok, true);
  l.release();
  const fourth = l.tryAcquire();
  assert.strictEqual(fourth.ok, false);
  assert.strictEqual(fourth.reason, 'rate-ceiling');
  now += 1001; // window rolls
  assert.strictEqual(l.tryAcquire().ok, true);
});

test('daily budget caps total spawns even under the per-minute ceiling', () => {
  let now = 0;
  // High concurrency + high per-window ceiling, but only 2 runs/day allowed.
  const l = new SpawnLimiter({ maxConcurrent: 100, ceiling: 100, windowMs: 1000, dailyBudget: 2, now: () => now });
  assert.strictEqual(l.tryAcquire().ok, true);
  l.release();
  now += 2000; // roll the per-minute window so rate-ceiling can't be the blocker
  assert.strictEqual(l.tryAcquire().ok, true);
  l.release();
  now += 2000;
  const third = l.tryAcquire();
  assert.strictEqual(third.ok, false);
  assert.strictEqual(third.reason, 'daily-budget');
  now += 24 * 60 * 60 * 1000 + 1; // a day later — budget resets
  assert.strictEqual(l.tryAcquire().ok, true);
});
