'use strict';

const { test } = require('node:test');
const assert = require('node:assert');
const crypto = require('crypto');

const { getTrigger } = require('../trigger');
const jira = require('../trigger/jira');
const jiraDc = require('../trigger/jira-dc');
const generic = require('../trigger/generic');

const HMAC = 'a'.repeat(64);
const SHARED = 's'.repeat(40);
const sign = (body) => 'sha256=' + crypto.createHmac('sha256', HMAC).update(body).digest('hex');
const def = (actors = ['ALLOWED-1']) => ({
  authorizedActors: new Set(actors),
  loopMarker: 'GENERATED BY AI',
});

// --- registry ----------------------------------------------------------------
test('registry resolves jira (default), jira-dc, and generic; throws on unknown', () => {
  assert.strictEqual(getTrigger(undefined).name, 'jira');
  assert.strictEqual(getTrigger('jira-dc').trigger, jiraDc);
  assert.strictEqual(getTrigger('generic').trigger, generic);
  assert.throws(() => getTrigger('nope'), /unknown TRIGGER/);
});

// --- jira: authenticate ------------------------------------------------------
test('jira authenticates via HMAC and via shared secret', () => {
  const body = Buffer.from('{"a":1}');
  assert.deepStrictEqual(jira.authenticate({ 'x-hub-signature': sign(body) }, body, { hmac: HMAC }), {
    ok: true,
    via: 'hmac',
  });
  assert.deepStrictEqual(
    jira.authenticate({ 'x-triage-token': SHARED }, Buffer.from('{}'), { hmac: HMAC, sharedSecret: SHARED }),
    { ok: true, via: 'shared-secret' }
  );
  assert.strictEqual(jira.authenticate({}, Buffer.from('{}'), { hmac: HMAC }).ok, false);
});

// --- jira: decide (stateless — payload + agent def only) ---------------------
test('jira: issue_created spawns with the key as a var', () => {
  const v = jira.decide(
    { webhookEvent: 'jira:issue_created', user: { accountId: 'X' }, issue: { key: 'KAN-9' } },
    def()
  );
  assert.deepStrictEqual(v, { action: 'spawn', vars: { key: 'KAN-9' } });
});

test('jira: issue_updated WITH triage label by allowed actor spawns; WITHOUT label is ineligible', () => {
  const withLabel = jira.decide(
    {
      webhookEvent: 'jira:issue_updated',
      user: { accountId: 'ALLOWED-1' },
      issue: { key: 'KAN-5' },
      changelog: { items: [{ field: 'labels', fromString: '', toString: 'triage' }] },
    },
    def()
  );
  assert.deepStrictEqual(withLabel, { action: 'spawn', vars: { key: 'KAN-5' } });
  const noLabel = jira.decide(
    {
      webhookEvent: 'jira:issue_updated',
      user: { accountId: 'ALLOWED-1' },
      issue: { key: 'KAN-5' },
      changelog: { items: [{ field: 'summary', fromString: 'a', toString: 'b' }] },
    },
    def()
  );
  assert.strictEqual(noLabel.action, 'drop');
  assert.match(noLabel.reason, /ineligible/);
});

test('jira.triageLabelAdded detects an add vs a pre-existing label', () => {
  assert.strictEqual(
    jira.triageLabelAdded({ changelog: { items: [{ field: 'labels', fromString: 'x', toString: 'x triage' }] } }),
    true
  );
  assert.strictEqual(
    jira.triageLabelAdded({ changelog: { items: [{ field: 'labels', fromString: 'triage', toString: 'triage done' }] } }),
    false
  );
});

test('jira: automation label-add from allowed actor spawns; unauthorized drops', () => {
  const ok = jira.decide(
    { webhookEvent: 'automation:label-added', user: { accountId: 'ALLOWED-1' }, issue: { key: 'KAN-1' } },
    def()
  );
  assert.deepStrictEqual(ok, { action: 'spawn', vars: { key: 'KAN-1' } });
  const bad = jira.decide(
    { webhookEvent: 'automation:label-added', user: { accountId: 'OUTSIDER' }, issue: { key: 'KAN-1' } },
    def()
  );
  assert.strictEqual(bad.action, 'drop');
  assert.match(bad.reason, /unauthorized/);
});

test('jira: stateless loop guard drops the agent self-write by its loop marker', () => {
  const v = jira.decide(
    {
      webhookEvent: 'jira:issue_updated',
      user: { accountId: 'SOMEONE' },
      issue: { key: 'KAN-1' },
      comment: { body: 'prefix GENERATED BY AI suffix' },
    },
    def()
  );
  assert.strictEqual(v.action, 'drop');
  assert.match(v.reason, /marker/);
});

test('jira.dedupeId prefers the native id, falls back to the delivery id', () => {
  assert.strictEqual(jira.dedupeId({ 'x-atlassian-webhook-identifier': 'wid' }), 'wid');
  assert.strictEqual(jira.dedupeId({ 'x-triage-delivery-id': 'del' }), 'del');
});

// --- jira-dc (Data Center): actor by username/key, synthetic dedupe id --------
test('jira-dc authenticates the same two ways (HMAC + shared secret)', () => {
  const body = Buffer.from('{"a":1}');
  assert.strictEqual(jiraDc.authenticate({ 'x-hub-signature': sign(body) }, body, { hmac: HMAC }).ok, true);
  assert.strictEqual(
    jiraDc.authenticate({ 'x-triage-token': SHARED }, Buffer.from('{}'), { hmac: HMAC, sharedSecret: SHARED }).ok,
    true
  );
  assert.strictEqual(jiraDc.authenticate({}, Buffer.from('{}'), { hmac: HMAC }).ok, false);
});

test('jira-dc: actor allowlist keys on user.name (and falls back to user.key)', () => {
  // DC sends user.name (login), not accountId. An allowed username spawns.
  const byName = jiraDc.decide(
    { webhookEvent: 'automation:label-added', user: { name: 'jdoe' }, issue: { key: 'OPS-1' } },
    def(['jdoe'])
  );
  assert.deepStrictEqual(byName, { action: 'spawn', vars: { key: 'OPS-1' } });
  // user.key works when name is absent.
  const byKey = jiraDc.decide(
    { webhookEvent: 'automation:label-added', user: { key: 'JIRAUSER10001' }, issue: { key: 'OPS-2' } },
    def(['JIRAUSER10001'])
  );
  assert.deepStrictEqual(byKey, { action: 'spawn', vars: { key: 'OPS-2' } });
  // A Cloud-style accountId is NOT accepted as the DC actor.
  const byAccountId = jiraDc.decide(
    { webhookEvent: 'automation:label-added', user: { accountId: 'jdoe' }, issue: { key: 'OPS-3' } },
    def(['jdoe'])
  );
  assert.strictEqual(byAccountId.action, 'drop');
  assert.match(byAccountId.reason, /unauthorized/);
});

test('jira-dc: issue_updated with triage label added by allowed user spawns', () => {
  const v = jiraDc.decide(
    {
      webhookEvent: 'jira:issue_updated',
      user: { name: 'jdoe' },
      issue: { key: 'OPS-5' },
      changelog: { items: [{ field: 'labels', fromString: '', toString: 'triage' }] },
    },
    def(['jdoe'])
  );
  assert.deepStrictEqual(v, { action: 'spawn', vars: { key: 'OPS-5' } });
});

test('jira-dc: stateless loop guard drops the agent self-write by its loop marker', () => {
  const v = jiraDc.decide(
    {
      webhookEvent: 'jira:issue_updated',
      user: { name: 'someone' },
      issue: { key: 'OPS-1' },
      comment: { body: 'prefix GENERATED BY AI suffix' },
    },
    def()
  );
  assert.strictEqual(v.action, 'drop');
  assert.match(v.reason, /marker/);
});

test('jira-dc.dedupeId: header wins, else synthesizes key-changelogId, else key', () => {
  assert.strictEqual(jiraDc.dedupeId({ 'x-triage-delivery-id': 'del' }, {}), 'del');
  assert.strictEqual(jiraDc.dedupeId({}, { issue: { key: 'OPS-5' }, changelog: { id: '90210' } }), 'OPS-5-90210');
  assert.strictEqual(jiraDc.dedupeId({}, { issue: { key: 'OPS-5' } }), 'OPS-5');
  assert.strictEqual(jiraDc.dedupeId({}, {}), undefined);
});

// --- generic -----------------------------------------------------------------
test('generic passes the body through as prompt vars, no eligibility gate', () => {
  const v = generic.decide({ vars: { repo: 'acme', pr: 42 } });
  assert.deepStrictEqual(v, { action: 'spawn', vars: { repo: 'acme', pr: 42 } });
  // A flat object with no `vars` wrapper is used directly.
  const flat = generic.decide({ key: 'X', foo: 'bar' });
  assert.deepStrictEqual(flat, { action: 'spawn', vars: { key: 'X', foo: 'bar' } });
});

test('generic authenticates the same two ways', () => {
  const body = Buffer.from('{"vars":{}}');
  assert.strictEqual(generic.authenticate({ 'x-hub-signature': sign(body) }, body, { hmac: HMAC }).ok, true);
  assert.strictEqual(
    generic.authenticate({ 'x-triage-token': SHARED }, body, { hmac: HMAC, sharedSecret: SHARED }).ok,
    true
  );
});
