'use strict';

const { test } = require('node:test');
const assert = require('node:assert');
const crypto = require('crypto');

// The Jira trigger reads its bot accountId from env at module load (it's the
// trigger's own config now, not engine state) — set it BEFORE requiring.
process.env.JIRA_BOT_ACCOUNT_ID = 'BOT-1';

const { getTrigger } = require('../trigger');
const jira = require('../trigger/jira');
const generic = require('../trigger/generic');

const HMAC = 'a'.repeat(40);
const SHARED = 's'.repeat(40);
const sign = (body) => 'sha256=' + crypto.createHmac('sha256', HMAC).update(body).digest('hex');
const def = (actors = ['ALLOWED-1']) => ({ authorizedActors: new Set(actors) });

// --- registry ----------------------------------------------------------------
test('registry resolves jira (default) and generic; throws on unknown', () => {
  assert.strictEqual(getTrigger(undefined).name, 'jira');
  assert.strictEqual(getTrigger('generic').trigger, generic);
  assert.throws(() => getTrigger('nope'), /unknown TRIGGER/);
});

// --- jira: authenticate ------------------------------------------------------
test('jira authenticates via HMAC and via shared secret', () => {
  const body = Buffer.from('{"a":1}');
  assert.deepStrictEqual(jira.authenticate({ 'x-hub-signature': sign(body) }, body, { hmac: HMAC }), {
    ok: true,
    via: 'hmac',
  });
  assert.deepStrictEqual(
    jira.authenticate({ 'x-triage-token': SHARED }, Buffer.from('{}'), { hmac: HMAC, sharedSecret: SHARED }),
    { ok: true, via: 'shared-secret' }
  );
  assert.strictEqual(jira.authenticate({}, Buffer.from('{}'), { hmac: HMAC }).ok, false);
});

// --- jira: decide (parity with the old gate logic) ---------------------------
// Bot accountId comes from JIRA_BOT_ACCOUNT_ID (set above); state only carries
// the agent's loop marker now.
const state = () => ({ loopMarker: 'GENERATED BY AI' });

test('jira: issue_created spawns with the key as a var', () => {
  const v = jira.decide(
    { webhookEvent: 'jira:issue_created', user: { accountId: 'X' }, issue: { key: 'KAN-9' } },
    def(),
    state()
  );
  assert.deepStrictEqual(v, { action: 'spawn', vars: { key: 'KAN-9' } });
});

test('jira: issue_updated WITH triage label by allowed actor spawns; WITHOUT label is ineligible', () => {
  const withLabel = jira.decide(
    {
      webhookEvent: 'jira:issue_updated',
      user: { accountId: 'ALLOWED-1' },
      issue: { key: 'KAN-5' },
      changelog: { items: [{ field: 'labels', fromString: '', toString: 'triage' }] },
    },
    def(),
    state()
  );
  assert.deepStrictEqual(withLabel, { action: 'spawn', vars: { key: 'KAN-5' } });
  const noLabel = jira.decide(
    {
      webhookEvent: 'jira:issue_updated',
      user: { accountId: 'ALLOWED-1' },
      issue: { key: 'KAN-5' },
      changelog: { items: [{ field: 'summary', fromString: 'a', toString: 'b' }] },
    },
    def(),
    state()
  );
  assert.strictEqual(noLabel.action, 'drop');
  assert.match(noLabel.reason, /ineligible/);
});

test('jira.triageLabelAdded detects an add vs a pre-existing label', () => {
  assert.strictEqual(
    jira.triageLabelAdded({ changelog: { items: [{ field: 'labels', fromString: 'x', toString: 'x triage' }] } }),
    true
  );
  assert.strictEqual(
    jira.triageLabelAdded({ changelog: { items: [{ field: 'labels', fromString: 'triage', toString: 'triage done' }] } }),
    false
  );
});

test('jira: automation label-add from allowed actor spawns; unauthorized drops', () => {
  const ok = jira.decide(
    { webhookEvent: 'automation:label-added', user: { accountId: 'ALLOWED-1' }, issue: { key: 'KAN-1' } },
    def(),
    state()
  );
  assert.deepStrictEqual(ok, { action: 'spawn', vars: { key: 'KAN-1' } });
  const bad = jira.decide(
    { webhookEvent: 'automation:label-added', user: { accountId: 'OUTSIDER' }, issue: { key: 'KAN-1' } },
    def(),
    state()
  );
  assert.strictEqual(bad.action, 'drop');
  assert.match(bad.reason, /unauthorized/);
});

test('jira: loop guard drops bot self-writes (by actor and by marker)', () => {
  const byActor = jira.decide(
    { webhookEvent: 'jira:issue_created', user: { accountId: 'BOT-1' }, issue: { key: 'KAN-1' } },
    def(),
    state()
  );
  assert.strictEqual(byActor.action, 'drop');
  const byMarker = jira.decide(
    {
      webhookEvent: 'jira:issue_updated',
      user: { accountId: 'SOMEONE' },
      issue: { key: 'KAN-1' },
      comment: { body: 'prefix GENERATED BY AI suffix' },
    },
    def(),
    { ...state(), botActor: null }
  );
  assert.strictEqual(byMarker.action, 'drop');
  assert.match(byMarker.reason, /marker/);
});

test('jira.dedupeId prefers the native id, falls back to the delivery id', () => {
  assert.strictEqual(jira.dedupeId({ 'x-atlassian-webhook-identifier': 'wid' }), 'wid');
  assert.strictEqual(jira.dedupeId({ 'x-triage-delivery-id': 'del' }), 'del');
});

// --- generic -----------------------------------------------------------------
test('generic passes the body through as prompt vars, no eligibility gate', () => {
  const v = generic.decide({ vars: { repo: 'acme', pr: 42 } });
  assert.deepStrictEqual(v, { action: 'spawn', vars: { repo: 'acme', pr: 42 } });
  // A flat object with no `vars` wrapper is used directly.
  const flat = generic.decide({ key: 'X', foo: 'bar' });
  assert.deepStrictEqual(flat, { action: 'spawn', vars: { key: 'X', foo: 'bar' } });
});

test('generic authenticates the same two ways (neutral default header)', () => {
  const body = Buffer.from('{"vars":{}}');
  assert.strictEqual(generic.authenticate({ 'x-hub-signature': sign(body) }, body, { hmac: HMAC }).ok, true);
  assert.strictEqual(
    generic.authenticate({ 'x-agent-token': SHARED }, body, { hmac: HMAC, sharedSecret: SHARED }).ok,
    true
  );
});
