'use strict';

// COMPATIBILITY SHIM. The gate's logic moved to:
//   - src/auth.js          → verifySignature / verifySharedSecret (crypto)
//   - src/trigger/jira.js   → Jira eligibility/loop-guard/authz (decide)
//   - src/agent-def.js      → the prompt + loop marker (now skill-defined)
//
// server.js no longer imports this file; it's kept so older imports and tests
// referencing `./gate` still resolve. New code should use auth.js + the trigger
// registry directly.

const { verifySignature, verifySharedSecret, SIGNATURE_ALGO } = require('./auth');
const jira = require('../trigger/jira');

// The triage skill's loop-marker sentinel, kept here for the cross-language
// substring test that pins jira.sh's disclaimer wording. The runtime value now
// comes from the agent definition (SKILL.md frontmatter `loopMarker`).
const TRIAGE_MARKER = 'This was generated by AI during triage.';

/**
 * Back-compat decide(): adapts the old (payload, state{botAccountId,
 * authorizedActors, triageMarker}) signature to the Jira trigger adapter, and
 * maps its { vars:{key} } back to the legacy { action:'spawn', key } shape.
 */
function decide(payload, state) {
  const def = { authorizedActors: state.authorizedActors || new Set() };
  const adapterState = { botActor: state.botAccountId, loopMarker: state.triageMarker };
  const v = jira.decide(payload, def, adapterState);
  if (v.action === 'spawn') return { action: 'spawn', key: v.vars.key };
  // Normalize the loop-guard reason text to the legacy phrasing the old tests used.
  if (v.reason === 'loop-guard: bot actor') return { action: 'drop', reason: 'loop-guard: bot accountId' };
  return v;
}

module.exports = {
  verifySignature,
  verifySharedSecret,
  SIGNATURE_ALGO,
  decide,
  triageLabelAdded: jira.triageLabelAdded,
  payloadCarriesMarker: jira.payloadCarriesMarker,
  TRIGGER_LABEL: jira.TRIGGER_LABEL,
  AUTOMATION_LABEL_EVENT: jira.AUTOMATION_LABEL_EVENT,
  TRIAGE_MARKER,
};
