#!/usr/bin/env bash
# jira.sh — thin, auditable wrapper over the Jira Cloud REST API v3 for the
# triage agent. The agent (pi) calls these subcommands; all writes are bounded.
#
# Auth: Basic, pre-computed so the token never appears inline in a command the
# pi --mode json event stream would log to stdout (R2a-adjacent log hygiene).
# Reads JIRA_EMAIL + JIRA_API_TOKEN + JIRA_BASE_URL from the environment.
#
# Allowed-value enforcement (R2): set-fields/assign/transition reject any value
# not present in the config (TRIAGE_CONFIG, default /etc/triage/config.json).
# When the config is absent or a set is empty, writes FAIL CLOSED.
#
# Convergent writes (KTD5): set-fields reads current state and writes only the
# fields that differ, so replays are no-ops.
#
# Step 0.5 probe (2026-06-02, henriquegraca.atlassian.net / KAN) CONFIRMED the
# v3 shapes used here against the live API:
#   - priority via fields.priority.name        → 204 ✅
#   - labels via update.labels [{add}/{remove}] → 204 ✅
#   - issuetype via fields.issuetype.name       → 204 ✅ (plain field edit, NOT a
#     transition-with-screen — Task↔Story swapped cleanly)
#   - comment ADF {type:doc,version:1,...}      → 201 ✅
#   - transitions: To Do=11, In Progress=21, In Review=31, Done=41
# No remaining VERIFY items for these paths.
set -euo pipefail

: "${JIRA_BASE_URL:?JIRA_BASE_URL is required (https://your-site.atlassian.net)}"
: "${JIRA_EMAIL:?JIRA_EMAIL is required}"
: "${JIRA_API_TOKEN:?JIRA_API_TOKEN is required}"
TRIAGE_CONFIG="${TRIAGE_CONFIG:-/etc/triage/config.json}"

# Pre-compute the Basic credential once; pass via header, never on the command
# line as -u (keeps it out of any process/arg logging).
_AUTH="$(printf '%s:%s' "$JIRA_EMAIL" "$JIRA_API_TOKEN" | base64 | tr -d '\n')"

_api() {
  # _api METHOD PATH [json-body]
  local method="$1" path="$2" body="${3:-}"
  local url="${JIRA_BASE_URL%/}/rest/api/3${path}"
  if [ -n "$body" ]; then
    curl -sS -X "$method" "$url" \
      -H "Authorization: Basic ${_AUTH}" \
      -H "Content-Type: application/json" \
      -H "Accept: application/json" \
      --data "$body" \
      --fail-with-body
  else
    curl -sS -X "$method" "$url" \
      -H "Authorization: Basic ${_AUTH}" \
      -H "Accept: application/json" \
      --fail-with-body
  fi
}

_die() { echo "jira.sh: $*" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || _die "jq is required"

# _allowed FIELD VALUE — exit 0 if VALUE is in the allowed set for FIELD.
# Config shape: { "labels": [...], "priorities": [...], "assignees": [...],
#                 "issuetypes": [...] }. Fail closed if config or set missing.
_allowed() {
  local field="$1" value="$2"
  [ -f "$TRIAGE_CONFIG" ] || _die "allowed-set config $TRIAGE_CONFIG missing — failing closed"
  local hit
  hit="$(jq -r --arg f "$field" --arg v "$value" \
    '(.[$f] // []) | index($v) | if . == null then "no" else "yes" end' "$TRIAGE_CONFIG")"
  [ "$hit" = "yes" ]
}

cmd_get() {
  # get KEY — full issue (fields + changelog)
  local key="${1:?usage: get KEY}"
  _api GET "/issue/${key}?expand=changelog"
}

cmd_myself() {
  # myself — the authenticated bot account (used to confirm identity)
  _api GET "/myself"
}

cmd_comment() {
  # comment KEY TEXT — posts a comment. The disclaimer sentinel is prepended
  # here (KTD5) so every triage comment is recognizable as the bot's own write.
  local key="${1:?usage: comment KEY TEXT}" text="${2:?usage: comment KEY TEXT}"
  local disclaimer="> *This was generated by AI during triage.*"
  # ADF body — confirmed accepted by the live v3 API (Step 0.5 probe).
  local body
  body="$(jq -n --arg d "$disclaimer" --arg t "$text" '{
    body: {
      type: "doc", version: 1,
      content: [
        { type: "paragraph", content: [ { type: "text", text: $d } ] },
        { type: "paragraph", content: [ { type: "text", text: $t } ] }
      ]
    }
  }')"
  _api POST "/issue/${key}/comment" "$body"
}

cmd_set_fields() {
  # set-fields KEY priority=NAME label=NAME [label=NAME ...] issuetype=NAME
  # Convergent: reads current values, writes only what differs, after the
  # allowed-set guard. Labels are additive within the allowed set.
  local key="${1:?usage: set-fields KEY field=value ...}"; shift
  local current; current="$(cmd_get "$key")"
  local update='{}' fields='{}'
  local add_labels=()
  local p_name="" it_name=""

  for kv in "$@"; do
    local f="${kv%%=*}" v="${kv#*=}"
    case "$f" in
      priority)
        _allowed priorities "$v" || _die "priority '$v' not in allowed set"
        p_name="$v" ;;
      label)
        _allowed labels "$v" || _die "label '$v' not in allowed set"
        add_labels+=("$v") ;;
      issuetype)
        _allowed issuetypes "$v" || _die "issuetype '$v' not in allowed set"
        it_name="$v" ;;
      *) _die "unknown field '$f'" ;;
    esac
  done

  # Priority: write only if different.
  if [ -n "$p_name" ]; then
    local cur_p; cur_p="$(echo "$current" | jq -r '.fields.priority.name // ""')"
    if [ "$cur_p" != "$p_name" ]; then
      fields="$(echo "$fields" | jq --arg n "$p_name" '. + {priority: {name: $n}}')"
    fi
  fi

  # Labels: add only those not already present (convergent).
  if [ "${#add_labels[@]}" -gt 0 ]; then
    local ops='[]'
    for l in "${add_labels[@]}"; do
      local has; has="$(echo "$current" | jq -r --arg l "$l" '(.fields.labels // []) | index($l) | if .==null then "no" else "yes" end')"
      [ "$has" = "yes" ] || ops="$(echo "$ops" | jq --arg l "$l" '. + [{add: $l}]')"
    done
    [ "$(echo "$ops" | jq 'length')" -gt 0 ] && update="$(echo "$update" | jq --argjson o "$ops" '. + {labels: $o}')"
  fi

  # Issue type — plain field edit, confirmed by the Step 0.5 probe (Task↔Story
  # swapped via fields.issuetype.name with HTTP 204; no transition screen
  # needed on this project's workflow).
  if [ -n "$it_name" ]; then
    local cur_it; cur_it="$(echo "$current" | jq -r '.fields.issuetype.name // ""')"
    if [ "$cur_it" != "$it_name" ]; then
      fields="$(echo "$fields" | jq --arg n "$it_name" '. + {issuetype: {name: $n}}')"
    fi
  fi

  # Nothing to do? convergent no-op.
  if [ "$fields" = '{}' ] && [ "$update" = '{}' ]; then
    echo '{"status":"noop","reason":"already at target state"}'
    return 0
  fi

  local payload; payload="$(jq -n --argjson f "$fields" --argjson u "$update" '{fields: $f, update: $u}')"
  _api PUT "/issue/${key}" "$payload"
  echo "{\"status\":\"updated\",\"key\":\"${key}\"}"
}

cmd_assign() {
  # assign KEY ACCOUNT_ID — assignee restricted to the allowed pool (R2c: real
  # on-call accounts only). Convergent: skip if already assigned to target.
  local key="${1:?usage: assign KEY ACCOUNT_ID}" acct="${2:?usage: assign KEY ACCOUNT_ID}"
  _allowed assignees "$acct" || _die "assignee '$acct' not in allowed pool"
  local cur; cur="$(cmd_get "$key" | jq -r '.fields.assignee.accountId // ""')"
  if [ "$cur" = "$acct" ]; then echo '{"status":"noop"}'; return 0; fi
  _api PUT "/issue/${key}/assignee" "$(jq -n --arg a "$acct" '{accountId: $a}')"
  echo "{\"status\":\"assigned\",\"key\":\"${key}\"}"
}

cmd_transitions() {
  # transitions KEY — list available transition ids/names
  local key="${1:?usage: transitions KEY}"
  _api GET "/issue/${key}/transitions"
}

cmd_transition() {
  # transition KEY TRANSITION_ID — move the issue through a workflow transition.
  # Guarded by an allowed-set (config "transitions") so a prompt-injected agent
  # can't move a ticket to an arbitrary status. Fails closed when the set is
  # absent or empty.
  # Used for workflow status changes (To Do=11, In Progress=21, In Review=31,
  # Done=41 on the KAN workflow per the Step 0.5 probe). Issue-type changes do
  # NOT need this — they go through set-fields as a plain field edit.
  local key="${1:?usage: transition KEY TRANSITION_ID}" tid="${2:?usage: transition KEY TRANSITION_ID}"
  _allowed transitions "$tid" || _die "transition '$tid' not in allowed set"
  _api POST "/issue/${key}/transitions" "$(jq -n --arg t "$tid" '{transition: {id: $t}}')"
  echo "{\"status\":\"transitioned\",\"key\":\"${key}\"}"
}

cmd_add_label() {
  # add-label KEY LABEL — convenience for adding a single label (e.g. needs-human).
  local key="${1:?usage: add-label KEY LABEL}" label="${2:?usage: add-label KEY LABEL}"
  _allowed labels "$label" || _die "label '$label' not in allowed set"
  _api PUT "/issue/${key}" "$(jq -n --arg l "$label" '{update: {labels: [{add: $l}]}}')"
  echo "{\"status\":\"labeled\",\"key\":\"${key}\",\"label\":\"${label}\"}"
}

cmd_remove_label() {
  # remove-label KEY LABEL — clears the `triage` work-queue flag (R6a). Restricted
  # to the trigger label ONLY, so an injected agent can't strip protective
  # labels off a ticket. The trigger label is configurable via TRIGGER_LABEL
  # (default "triage") to match the listener's gate.
  local key="${1:?usage: remove-label KEY LABEL}" label="${2:?usage: remove-label KEY LABEL}"
  local trigger="${TRIGGER_LABEL:-triage}"
  [ "$label" = "$trigger" ] || _die "remove-label only permitted for the trigger label '$trigger', got '$label'"
  _api PUT "/issue/${key}" "$(jq -n --arg l "$label" '{update: {labels: [{remove: $l}]}}')"
  echo "{\"status\":\"unlabeled\",\"key\":\"${key}\",\"label\":\"${label}\"}"
}

main() {
  local sub="${1:?usage: jira.sh <get|myself|comment|set-fields|assign|transitions|transition|add-label|remove-label> ...}"
  shift || true
  case "$sub" in
    get)           cmd_get "$@" ;;
    myself)        cmd_myself "$@" ;;
    comment)       cmd_comment "$@" ;;
    set-fields)    cmd_set_fields "$@" ;;
    assign)        cmd_assign "$@" ;;
    transitions)   cmd_transitions "$@" ;;
    transition)    cmd_transition "$@" ;;
    add-label)     cmd_add_label "$@" ;;
    remove-label)  cmd_remove_label "$@" ;;
    *) _die "unknown subcommand '$sub'" ;;
  esac
}

main "$@"
