#!/usr/bin/env bash
# Self-contained test harness for the triage skill scripts.
#
# No external test framework: we stub `curl` with a fake on PATH that replays a
# fixture for GETs and records the request body/URL for writes, then assert on
# the scripts' deterministic behavior (allowed-set guard, fail-closed,
# convergent no-op, structured gitlab output). The unverified live-API shapes
# (issue-type mechanism, ADF) are NOT asserted here — those are confirmed in the
# Step 0.5 probe and captured as real fixtures later.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$HERE/.." && pwd)"
SCRIPTS="$SKILL_DIR/scripts"
FIX="$HERE/fixtures"

PASS=0; FAIL=0
ok()   { PASS=$((PASS+1)); echo "ok   - $1"; }
nope() { FAIL=$((FAIL+1)); echo "FAIL - $1"; [ -n "${2:-}" ] && echo "       $2"; }

# --- fake curl ----------------------------------------------------------------
# Writes captured request to $CURL_CAPTURE; emits $CURL_FIXTURE for the body.
STUB_DIR="$(mktemp -d)"
trap 'rm -rf "$STUB_DIR"' EXIT
cat > "$STUB_DIR/curl" <<'STUB'
#!/usr/bin/env bash
# Record args (URL + --data body) for assertions; reply with the fixture file.
cap="${CURL_CAPTURE:-/dev/null}"
body=""
url=""
prev=""
for a in "$@"; do
  case "$prev" in
    --data) body="$a" ;;
  esac
  case "$a" in
    http*|https*) url="$a" ;;
  esac
  prev="$a"
done
{ echo "URL=$url"; echo "BODY=$body"; } >> "$cap"
[ -n "${CURL_FIXTURE:-}" ] && cat "$CURL_FIXTURE"
exit 0
STUB
chmod +x "$STUB_DIR/curl"
export PATH="$STUB_DIR:$PATH"

# --- common env ---------------------------------------------------------------
export JIRA_BASE_URL="https://example.atlassian.net"
export JIRA_EMAIL="bot@example.com"
export JIRA_API_TOKEN="test-token"
export TRIAGE_CONFIG="$HERE/config.test.json"

run_jira()  { CURL_CAPTURE="$1" CURL_FIXTURE="$2"; export CURL_CAPTURE CURL_FIXTURE; shift 2; bash "$SCRIPTS/jira.sh" "$@"; }

# --- T1: allowed-set guard rejects out-of-set label ---------------------------
cap="$(mktemp)"
if out="$(run_jira "$cap" "$FIX/issue-KAN-5.json" set-fields KAN-5 label=not-a-real-label 2>&1)"; then
  nope "T1 out-of-set label rejected" "expected non-zero exit, got success: $out"
else
  echo "$out" | grep -q "not in allowed set" && ok "T1 out-of-set label rejected" || nope "T1 out-of-set label rejected" "$out"
fi

# --- T2: fail closed when config missing --------------------------------------
cap="$(mktemp)"
if out="$(TRIAGE_CONFIG=/nonexistent/config.json run_jira "$cap" "$FIX/issue-KAN-5.json" set-fields KAN-5 priority=Low 2>&1)"; then
  nope "T2 fail-closed on missing config" "expected failure, got: $out"
else
  echo "$out" | grep -q "failing closed" && ok "T2 fail-closed on missing config" || nope "T2 fail-closed on missing config" "$out"
fi

# --- T3: convergent no-op (priority already at target) ------------------------
# Fixture has priority Medium; setting Medium again should be a no-op (no PUT).
cap="$(mktemp)"
out="$(run_jira "$cap" "$FIX/issue-KAN-5.json" set-fields KAN-5 priority=Medium 2>&1)"
if echo "$out" | grep -q '"status":"noop"'; then
  # And no write URL (PUT /issue/KAN-5) should have been captured beyond the GET.
  if grep -q "URL=.*/issue/KAN-5$" "$cap"; then
    nope "T3 convergent no-op" "a PUT was issued despite no change: $(cat "$cap")"
  else
    ok "T3 convergent no-op"
  fi
else
  nope "T3 convergent no-op" "$out"
fi

# --- T4: assignee outside allowed pool rejected -------------------------------
cap="$(mktemp)"
if out="$(run_jira "$cap" "$FIX/issue-KAN-5.json" assign KAN-5 evil-account-id 2>&1)"; then
  nope "T4 assignee pool enforced" "expected rejection, got: $out"
else
  echo "$out" | grep -q "not in allowed pool" && ok "T4 assignee pool enforced" || nope "T4 assignee pool enforced" "$out"
fi

# --- T5: in-set priority change issues a PUT with the right field -------------
cap="$(mktemp)"
out="$(run_jira "$cap" "$FIX/issue-KAN-5.json" set-fields KAN-5 priority=Low 2>&1)"
# Collapse to one line so the assertion is newline-tolerant (the captured body
# is pretty-printed JSON spanning multiple lines).
flat="$(tr -d '\n ' < "$cap")"
if echo "$flat" | grep -q '"priority":{"name":"Low"}'; then ok "T5 in-set priority PUT body"; else nope "T5 in-set priority PUT body" "$(cat "$cap")"; fi

# --- T6: comment body carries the disclaimer sentinel -------------------------
cap="$(mktemp)"
run_jira "$cap" "$FIX/issue-KAN-5.json" comment KAN-5 "category=bug, severity=medium" >/dev/null 2>&1
if grep -q 'This was generated by AI during triage' "$cap"; then ok "T6 disclaimer in comment body"; else nope "T6 disclaimer in comment body" "$(cat "$cap")"; fi

# --- T7: gitlab.sh emits ONLY {component, owner}, no extra fields -------------
cat > "$STUB_DIR/curl" <<'STUB'
#!/usr/bin/env bash
# Reply with a rich project payload that includes content-ish fields we must NOT leak.
cat <<'JSON'
{"name":"payments","namespace":{"full_path":"team/backend"},"description":"SECRET internal notes","readme":"do not leak me"}
JSON
STUB
chmod +x "$STUB_DIR/curl"
export GITLAB_BASE_URL="http://gitlab.example.svc"
export GITLAB_READ_TOKEN="ro-token"
out="$(bash "$SCRIPTS/gitlab.sh" route team/payments 2>&1)"
keys="$(echo "$out" | jq -r 'keys | join(",")' 2>/dev/null)"
if [ "$keys" = "component,owner" ] && ! echo "$out" | grep -qi "secret\|leak\|readme\|description"; then
  ok "T7 gitlab structured output only"
else
  nope "T7 gitlab structured output only" "got: $out"
fi

# --- T8: transition outside the allowed set is rejected ----------------------
cat > "$STUB_DIR/curl" <<'STUB'
#!/usr/bin/env bash
cap="${CURL_CAPTURE:-/dev/null}"; { echo "called"; } >> "$cap"; exit 0
STUB
chmod +x "$STUB_DIR/curl"
cap="$(mktemp)"
if out="$(CURL_CAPTURE="$cap" bash "$SCRIPTS/jira.sh" transition KAN-5 999 2>&1)"; then
  nope "T8 transition allowed-set enforced" "expected rejection, got: $out"
else
  echo "$out" | grep -q "not in allowed set" && ok "T8 transition allowed-set enforced" || nope "T8 transition allowed-set enforced" "$out"
fi

# --- T9: in-set transition is permitted (reaches the API) --------------------
cap="$(mktemp)"
CURL_CAPTURE="$cap" bash "$SCRIPTS/jira.sh" transition KAN-5 31 >/dev/null 2>&1
grep -q "called" "$cap" && ok "T9 in-set transition permitted" || nope "T9 in-set transition permitted" "no API call made"

# --- T10: remove-label only permits the trigger label ------------------------
cap="$(mktemp)"
if out="$(CURL_CAPTURE="$cap" bash "$SCRIPTS/jira.sh" remove-label KAN-5 ready-for-agent 2>&1)"; then
  nope "T10 remove-label restricted to trigger" "expected rejection, got: $out"
else
  echo "$out" | grep -q "only permitted for the trigger label" && ok "T10 remove-label restricted to trigger" || nope "T10 remove-label restricted to trigger" "$out"
fi

# --- T11: remove-label permits the triage trigger label ----------------------
cap="$(mktemp)"
CURL_CAPTURE="$cap" bash "$SCRIPTS/jira.sh" remove-label KAN-5 triage >/dev/null 2>&1
grep -q "called" "$cap" && ok "T11 remove-label clears triage flag" || nope "T11 remove-label clears triage flag" "no API call made"

# --- T12: in-set issue-type change emits the issuetype field -----------------
# Restore the fixture-replaying stub for set-fields (needs the GET response).
cat > "$STUB_DIR/curl" <<'STUB'
#!/usr/bin/env bash
cap="${CURL_CAPTURE:-/dev/null}"
body=""; url=""; prev=""
for a in "$@"; do
  case "$prev" in --data) body="$a" ;; esac
  case "$a" in http*|https*) url="$a" ;; esac
  prev="$a"
done
{ echo "URL=$url"; echo "BODY=$body"; } >> "$cap"
[ -n "${CURL_FIXTURE:-}" ] && cat "$CURL_FIXTURE"
exit 0
STUB
chmod +x "$STUB_DIR/curl"
cap="$(mktemp)"
run_jira "$cap" "$FIX/issue-KAN-5.json" set-fields KAN-5 issuetype=Bug >/dev/null 2>&1
flat="$(tr -d '\n ' < "$cap")"
if echo "$flat" | grep -q '"issuetype":{"name":"Bug"}'; then ok "T12 in-set issue-type PUT body"; else nope "T12 in-set issue-type PUT body" "$(cat "$cap")"; fi

# --- T13: cross-language marker contract -------------------------------------
# The listener's TRIAGE_MARKER (gate.js) must be a substring of the disclaimer
# jira.sh writes, or the stateless cold-start loop guard silently fails open.
GATE_MARKER="$(grep -oE "const TRIAGE_MARKER = '[^']+'" "$SKILL_DIR/../../listener/src/gate.js" 2>/dev/null | sed "s/.*'\\(.*\\)'.*/\\1/")"
SKILL_DISCLAIMER="$(grep -oE 'This was generated by AI during triage\.' "$SCRIPTS/jira.sh" | head -1)"
if [ -n "$GATE_MARKER" ] && printf '%s' "$SKILL_DISCLAIMER" | grep -qF "$GATE_MARKER"; then
  ok "T13 listener marker is a substring of jira.sh disclaimer"
else
  nope "T13 listener marker is a substring of jira.sh disclaimer" "gate='$GATE_MARKER' skill='$SKILL_DISCLAIMER'"
fi

echo "-----"
echo "PASS=$PASS FAIL=$FAIL"
[ "$FAIL" -eq 0 ]
